/*
 * JScrollingFrame.java
 *
 * Created on 10 December 2001, 20:35
 */

package jparticles.gui;

/**
 *
 * @author  carlos
 */
public class JScrollingFrame extends javax.swing.JFrame
{    
    /** Creates new form JScrollingFrame */
    public JScrollingFrame()
    {                 
        initComponents();        
    }
    public void add(javax.swing.JPanel panel)
    {
        jScrollPane1.setViewportView(panel);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    private void initComponents()//GEN-BEGIN:initComponents
    {
        jScrollPane1 = new javax.swing.JScrollPane();
        
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                exitForm(evt);
            }
        });
        
        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
        
        pack();
    }//GEN-END:initComponents
    
    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        new JScrollingFrame().show();
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
